language: node_js
node_js: node
cache:
  directories:
    - node_modules
before_script:
  - sudo apt-get -qq update # qq for less output
install:
  - yarn
script:
  - yarn build && stop 10
  # - zip -r latest *
  # - mkdir -p dpl_cd_upload_ui
  # - mv latest.zip dpl_cd_upload_ui/latest.zip
# deploy:
#   - provider: s3
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     skip_cleanup: true # prevents resetting and deleting all changes
#         on: &2
#       repo: GoWithMeL1FB/gowithme-api
#     bucket: gwmapi
#     region: us-west-1
#   - provider: codedeploy
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     bucket: gwmapi
#     key: latest.zip
#     bundle_type: zip
#     application: gowithme
#     deployment_group: GoWithMe-DepGrp
#     region: us-west-1c
#     on: *2